// custom-admin.js
CMS.registerEventListener({
  name: 'preSave',
  handler: ({ entry }) => {
    // e.g. inject a banner at top of every body
    const body = entry.get('body') || ''
    entry.get('body')?.setValue(`> **AUTOGENERATED**\n\n${body}`)
  }
})
